version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/vaccinationSystem

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
